# -*- coding: utf-8 -*-
"""Linear Search

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mV0-Dyu2qnNl0AZHr6aNM7SXIB_BAk-
"""

#Linear Search

import time

arr=list(map(int,input("Enter the array: ").split()))
target=int(input("Enter the element: "))

start=time.time()

for i in range(len(arr)):
    if arr[i]==target:
      break
else:
  print("Element not found")

end=time.time()

print("Element found at position: ",i)
print("Time Complexity:")
print("Best case: O(1)")
print("Average case: O(1)")
print("Worst case: O(n)")
print("Space Complexity: O(1)")
print("Execution Time: ",end-start," Seconds")